names=char('PAH6.2flx','PAH7.7flx','PAH8.3flx','PAH8.6flx','PAH11.3flx','PAH12.0flx', ...
           'PAH12.7flx','PAH17.0flx','H\alpha','OIII continuum','SII continumm','IRAC 5.7 \mum', ...
           'PACS 100 \mum','SPIRE 250 \mum','SPIRE 350 \mum','SPIRE 500 \mum','Dust luminosity','Dust Mass', ...
           'SFR', 'Stellar Mass', 'TIR', 'Total gas mass', 'RHI','Metallicity');